app/urls.py
from django.conf.urls import include, url
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from app import views

base = r'^%s' % settings.URL_ROOT
urlpatterns = [
    re_path(base + r'admin/', admin.site.urls, name='admin'),
    re_path(base + r'provider/', include(('provider.urls', 'provider'))),
    re_path(base + r'series/', include(('series.urls', 'series'))),
    re_path(base + r'fetcher/', include(('fetcher.urls', "fetcher"))),

    re_path(base + r'$', views.index, name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

provider/urls.py
from django.conf.urls import url

from provider import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<provider_id>\d+)/$', views.view, name='view'),
    url(r'^(?P<provider_id>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<provider_id>\d+)/delete/$', views.delete, name='delete'),

    # Base Provider
    url(r'^base/$', views.base_index, name='base_index'),
    url(r'^base/(?P<base_provider_id>\d+)/$',
        views.base_view, name='base_view'),
]

provider/models.py
import json

from django.db import models
from json_field import JSONField

from app.validators import json_schema_validator

class BaseProvider(models.Model):
    """
    The Base logic of a provider
    Requires a client side implementation
    No web interface to create or edit, this is admin only
    """
    name = models.CharField(max_length=160,
                            verbose_name="Base Provider's name")

    available_options = JSONField(default=json.dumps({"properties": {"id": {"type": "integer", "required": False, "title": "id"}}}),
                                  help_text="A JSON Schema of options that"
                                  " the base provider allows",
                                  validators=[json_schema_validator])

    def available_options_json(self):
        return json.dumps(self.available_options)

    def __str__(self):
        return self.name


class Provider(models.Model):
    """
    The Provider specific information to be able to fetch any series
    from the provider
    Does not needed client side implementation
    """
    base_provider = models.ForeignKey(BaseProvider)
    name = models.CharField(max_length=160,
                            verbose_name="Name of the provider")
    website = models.URLField(help_text="url to the provider's website",
                              verbose_name="Provider's website")

    regex_find_count = models.CharField(max_length=256,
                                        default="\d+",
                                        help_text="Regular expression used "
                                        "client side "
                                        "to extract the episode/chapter count "
                                        "from a file name")
    options = JSONField(help_text="JSON Object filled of BaseProvider's"
                                  " available_options with data")

    def __str__(self):
        return "{} ({})".format(self.name, self.base_provider.name)

    def base_provider_options_json(self):
        return json.dumps(self.options)

provider/models/base_provider.py
import json

from django.db import models
from jsonfield import JSONField

from app.validators import json_schema_validator

_default='''{
    "properties":
    {
        "id": {
            "title": "ID",
            "type": "integer"
            }
    },
    "required": ["id"]
}'''

class BaseProvider(models.Model):
    """
    The Base logic of a provider
    Requires a client side implementation
    No web interface to create or edit, this is admin only
    """
    name = models.CharField(max_length=160,
                            verbose_name="Base Provider's name")

    available_options = JSONField(help_text="A JSON Schema of options that"
                                  " the base provider allows",
                                  validators=[json_schema_validator],
                                  default=_default)


    def available_options_json(self):
        return json.dumps(self.available_options)

    def __str__(self):
        return self.name

provider/models/provider.py
import json

from django.db import models
from jsonfield import JSONField

from provider.models import BaseProvider


class Provider(models.Model):
    """
    The Provider specific information to be able to fetch any series
    from the provider
    Does not needed client side implementation
    """

    base_provider = models.ForeignKey(BaseProvider, on_delete=models.CASCADE)
    name = models.CharField(max_length=160,
                            verbose_name="Name of the provider")
    website = models.URLField(help_text="url to the provider's website",
                              verbose_name="Provider's website")

    regex_find_count = models.CharField(max_length=256,
                                        default="\d+",
                                        help_text="Regular expression used "
                                        "client side "
                                        "to extract the episode/chapter count "
                                        "from a file name")
    options = JSONField(help_text="JSON Object filled of BaseProvider's"
                                  " available_options with data",
                        blank=True, default={})

    def __str__(self):
        return "{} ({})".format(self.name, self.base_provider.name)

    def base_provider_options_json(self):
        """
        Get options as a JSON string
        """
        return json.dumps(self.options)

provider/forms.py
import json

from django import forms
from django.core.validators import ValidationError
from django.utils.translation import ugettext as _

from provider.models import BaseProvider, Provider
from app.validators import json_validator, regex_validator, json_schema_check


class ProviderForm(forms.ModelForm):

    class Meta:
        model = Provider
        fields = ['name',
                  'website',
                  'base_provider',
                  'regex_find_count',
                  'options']
        exclude = ()

    name = forms.CharField(label='Provider Name')
    website = forms.URLField(label="Webiste")

    base_provider = forms.ModelChoiceField(empty_label=None,
                                           queryset=BaseProvider.objects,
                                           label="Base Provider")
    regex_find_count = forms.CharField(max_length=256,
                                       label="Count Regex",
                                       validators=[regex_validator])

    options = forms.CharField(required=False,
                              widget=forms.HiddenInput(),
                              validators=[json_validator])

    def clean_options(self):
        value = self.cleaned_data['options']

        if not value:
            value_dict = {}
        elif type(value) is str:
            try:
                value_dict = json.loads(value)
            except Exception as e:
                raise e

        if type(value_dict) is dict:
            json_schema_check(value_dict,
                              self.cleaned_data['base_provider'].available_options)
            return value_dict
        else:
            raise ValidationError(
                _('Invalid input: Did not expect type %(type)s'),
                params={'type': type(value)}
            )

    def clean(self):
        clean_data = super(ProviderForm, self).clean()
        return clean_data

provider/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

from provider.models import Provider, BaseProvider
from provider.forms import ProviderForm


def index(request):
    providers = Provider.objects.all()
    if request.META.get('CONTENT_TYPE') == 'application/json':
        return render(request, 'provider/index.json',
                      {'providers': providers},
                      content_type='application/json')
    else:
        return render(request, 'provider/index.html',
                      {'providers': providers})


def view(request, provider_id):
    provider = get_object_or_404(Provider, pk=provider_id)
    return render(request, 'provider/view.html',
                  {'provider': provider})


def new(request):
    form = ProviderForm()
    if request.method == 'POST':
        form = ProviderForm(request.POST)
        form.full_clean()
        if form.is_valid():
            new_provider = form.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 "<strong>Success</strong> Created {}"
                                 .format(new_provider.name))
            return HttpResponseRedirect(reverse('provider:view',
                                                args=[new_provider.id]))
    return render(request, 'provider/new.html',
                  {'form': form})


def edit(request, provider_id):
    provider = get_object_or_404(Provider, pk=provider_id)
    form = ProviderForm(instance=provider)
    if request.method == 'POST':
        form = ProviderForm(request.POST, instance=provider)
        if form.is_valid():
            if form.has_changed():
                form.save()

                messages.add_message(request,
                                     messages.SUCCESS,
                                     "<strong>Success</strong> Edited {}"
                                     .format(provider.name))
            return HttpResponseRedirect(reverse('provider:view',
                                                args=[provider.id]))
    return render(request, 'provider/edit.html',
                  {'form': form,
                   'provider': provider})


def delete(request, provider_id):
    if request.method == 'POST':
        provider = get_object_or_404(Provider, pk=provider_id)
        messages.add_message(request,
                             messages.INFO,
                             "{} has been deleted"
                             .format(provider.name))
        provider.delete()
        return HttpResponseRedirect(reverse('provider:index'))
    else:
        return HttpResponseRedirect(reverse('provider:view',
                                            args=(provider_id)))


def base_index(request):
    if request.META.get('CONTENT_TYPE') == 'application/json':
        return render(request, 'provider/base_index.json',
                      {'base_providers': BaseProvider.objects.all()},
                      content_type='application/json')
    else:
        return render(request, 'provider/base_index.html',
                      {'base_providers': BaseProvider.objects.all()})


def base_view(request, base_provider_id):
    base_provider = get_object_or_404(BaseProvider, pk=base_provider_id)
    if request.META.get('CONTENT_TYPE') == 'application/json':
        return render(request, 'provider/base_view.json',
                      {'base_provider': base_provider},
                      content_type='application/json')
    else:
        return render(request, 'provider/base_view.html',
                      {'base_provider': base_provider})

provider/templates/provider/base_index.html
{% extends 'provider/index.html' %}

{% block title %}
Providers - Base - Index
{% endblock title %}

{% block header %}
<h1>Base Provider</h1>
{% endblock header %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li ><a href="{% url 'provider:index' %}">Provider</a></li>
  <li class="active">Base Provider</li>
</ol>
{% endblock breadcrumb %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    {% if base_providers|length == 0 %}
    <h4>No Base Providers avaiable</h4>
    <p>Please add some</p>
    {% else %}
    <ul>
      {% for base_provider in base_providers %}
      <li><a href="{% url 'provider:base_view' base_provider.id %}">{{ base_provider }}</a></li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock content %}

provider/templates/provider/base_view.html
{% extends 'provider/index.html' %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li ><a href="{% url 'provider:index' %}">Provider</a></li>
  <li ><a href="{% url 'provider:base_index' %}">Base Provider</a></li>
  <li class="active">{{ base_provider.name }}</li>
</ol>
{% endblock breadcrumb %}

{% block header %}
<h1>
  {{ base_provider.name }}
</h1>
{% endblock header %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <ul>
      <li>Available Options: <code>{{ base_provider.get_available_options }}</code></li>
    </ul>
  </div>
</div>
{% endblock content %}

provider/templates/provider/edit.html
{% extends 'provider/index.html' %}
{% load bootstrap3 %}

{% block title %}
Providers - Edit {{ provider.name }}
{% endblock title %}


{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'provider:index' %}">Providers</a></li>
  <li><a href="{% url 'provider:view' provider.id %}">{{ provider.name }}</a></li>
  <li class="active">Edit</li>
</ol>
{% endblock breadcrumb %}

{% block header %}
<h1>Edit Provider: {{ provider.name }}</h1>
{% endblock header %}

{% block content %}
<div class="row">
  <div class="col-md-4">
    <form action="{% url 'provider:edit' provider.id  %}" method="post" class="form well">
      {% csrf_token %}
      {% include 'provider/form_provider.html' with form=form %}

      <a class="btn btn-default" href="{% url 'provider:view' provider.id %}" >
        Back
      </a>
      <button type="submit" class="btn btn-primary pull-right">
        Sumbit
      </button>
    </form>
  </div>
</div>
{% endblock content %}

provider/templates/provider/form_provider.html
{% load bootstrap3 %}
{% load staticfiles %}

{% bootstrap_form_errors form %}
<div class="row">
  <div class="col-md-12">
    {% bootstrap_field  form.name %}
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    {% bootstrap_field form.website %}
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    {% bootstrap_field form.regex_find_count %}
    {% comment %}
    TODO: Add regex test bed for regex options
    {% endcomment %}
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    {% bootstrap_field  form.base_provider %}
  </div>
</div>
{% bootstrap_field  form.options %}
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <div id="base_provider_options">
        {% if provider and not provider.options == None %}
        {% for opt, val in provider.options.items %}
        <input name="{{ opt }}" value="{{ val }}"></input>
        {% endfor %}
        {% else %}
        <p>Loading additional options</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" src="{% static 'jsonform/deps/underscore.js' %}"></script>
<script type="text/javascript" src="{% static 'jsonform/deps/opt/jsv.js' %}"></script>
<script type="text/javascript" src="{% static 'jsonform/deps/opt/ace/ace.js' %}"></script>
<script type="text/javascript" src="{% static 'jsonform/lib/jsonform.js' %}"></script>

<script type="text/javascript" src="{% static 'js/options.js' %}"></script>
<script type="text/javascript">
  change_trigger('#id_base_provider', '{% url "provider:base_index" %}', '#base_provider_options', '#id_options');

  $('#id_base_provider').ready(function() {
    $('#id_base_provider').change();
  });
</script>

provider/templates/provider/index.html
{% extends 'base.html' %}

{% block title %}
Providers - Index
{% endblock title %}

{% block navbar_items %}
<li><a href="{% url 'series:index' %}">Series</a></li>
<li class="active"><a href="{% url 'provider:index' %}">Providers</a></li>
<li><a href="{% url 'fetcher:index' %}">Fetcher</a></li>
{% endblock navbar_items %}

{% block header %}
<h1>Providers
  <div class="pull-right">
    <a href="{% url 'provider:new' %}" class="btn btn-success">
      Create
    </a>
  </div>
</h1>
{% endblock header %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    {% if providers|length == 0 %}
    <h4>No Providers avaiable</h4>
    <p>Please add some</p>
    {% else %}
    <ul>
      {% for provider in providers %}
      <li><a href="{% url 'provider:view' provider.id  %}">{{ provider }}</a></li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock content %}

provider/templates/provider/new.html
{% extends 'provider/index.html' %}
{% load bootstrap3 %}

{% block title %}
Providers - New
{% endblock title %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'provider:index' %}">Providers</a></li>
  <li class="active">New</li>
</ol>
{% endblock breadcrumb %}

{% block header %}
<h1>Create Provider</h1>
{% endblock header %}

{% block content %}
<div class="row">
  <div class="col-md-4">
    <form action="{% url 'provider:new' %}" method="post" class="form well">
      {% csrf_token %}
      {% include 'provider/form_provider.html' with form=form %}

      <a href="{% url 'provider:index' %}" class="btn btn-default">
        Back
      </a>
      <button type="submit" class="btn btn-primary pull-right">
        Sumbit
      </button>
    </form>
  </div>
</div>
{% endblock content %}

provider/templates/provider/view.html
{% extends 'provider/index.html' %}

{% block title %}
Providers - {{ provider.name }}
{% endblock title %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li ><a href="{% url 'provider:index' %}">Providers</a></li>
  <li class="active">{{ provider.name }}</li>
</ol>
{% endblock breadcrumb %}

{% block header %}
<h1>
  {{ provider.name }}
  <small>({{ provider.base_provider.name }})</small>
</h1>
{% endblock header %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <ul>
      <li>Website: <a href="{{ provider.website }}">{{ provider.website }}</a></li>
      <li>Count Regex: <code>{{ provider.regex_find_count }}</code></li>
      {% if provider.options|length > 0 %}
      <li>
        <p>Addtional options for {{ provider.base_provider.name }}</p>
        <ul>
          {% for k,v in provider.options.items %}
          <li>{{ k }}: {{ v }}</li>
          {% endfor %}
        </ul>
      </li>
      {% endif %}
    </ul>
  </div>
</div>

<div class="row" id="view-controls">
  <div class="col-md-12">
    <a href="{% url 'provider:index' %}" class="btn btn-default">
      Back
    </a>
    <a href="{% url 'provider:edit' provider.id %}" class="btn btn-warning">
      Edit
    </a>
    <button type="button" class="btn btn-danger btn-sm pull-right" data-toggle="modal" data-target="#modal-delete">
      Delete
    </button>
  </div>
</div>


<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Are you sure?</h3>
      </div>
      <div class="modal-body">
        <p>
          Are you sure you want to delete {{ provider.name }}?
        </p>
      </div>
      <div class="modal-footer">
        <form action="{% url 'provider:delete' provider.id %}" method="post">
          {% csrf_token %}
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal" >Close</button>
          <button type="submit" class="btn btn-danger">
            Delete
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}