app/urls.py
from django.conf.urls import include, url
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from app import views

base = r'^%s' % settings.URL_ROOT
urlpatterns = [
    re_path(base + r'admin/', admin.site.urls, name='admin'),
    re_path(base + r'provider/', include(('provider.urls', 'provider'))),
    re_path(base + r'series/', include(('series.urls', 'series'))),
    re_path(base + r'fetcher/', include(('fetcher.urls', "fetcher"))),

    re_path(base + r'$', views.index, name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

series/urls.py
from django.conf.urls import url

from series import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<series_id>\d+)/$', views.view, name='view'),
    url(r'^(?P<series_id>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<series_id>\d+)/delete/$', views.delete, name='delete'),
    url(r'(?P<series_id>\d+)/count/$', views.count, name='count'),

    # Media Types
    url(r'^media/$', views.media_type_index, name='media_index'),
    url(r'^media/(?P<media_type_id>\d+)/$',
        views.media_type_view, name='media_view'),
]

series/models.py
import os
import re
import json
from datetime import time, datetime
from dateutil.relativedelta import relativedelta

from django.utils import timezone
from django.utils.translation import ugettext as _
from django.db import models
from django.core.exceptions import ValidationError

from app.validators import json_schema_validator
from app.storage import OverwriteStorage
from json_field import JSONField
from provider.models import Provider


class MediaType(models.Model):
    """
    Over arching difference between series
    provides more options for different media types
    """
    name = models.CharField(max_length=80,
                            help_text="Name of the media type")
    available_options = JSONField(default=json.dumps({"properties": {"id": {"type": "integer", "required": False, "title": "id"}}}),
                                  help_text="A JSON schema of options that"
                                  " the media type allows",
                                  validators=[json_schema_validator])

    def __str__(self):
        return self.name

    def get_available_options(self):
        return json.dumps(self.available_options)


def poster_path(instance, filename):
    path = 'series/poster'
    root, ext = os.path.splitext(filename)
    # get filename
    if instance:
        filename = '{}{}'.format(instance.id, ext)
    # return the whole path to the file
    return os.path.join(path, filename)


class Series(models.Model):
    provider = models.ForeignKey(Provider)
    title = models.CharField(max_length=160,
                             verbose_name="Name of the series")

    search_title = models.CharField(max_length=256,
                                    blank=True,
                                    default='',
                                    verbose_name="String to be used when searching for the series")

    save_path = models.CharField(max_length=256,
                                 default='',
                                 blank=True,
                                 verbose_name="Path to be sorted into")

    info_url = models.URLField(blank=True,
                               verbose_name="Information URL")

    start_date = models.DateField(default=None,
                                  null=True)
    end_date = models.DateField(default=None,
                                null=True)

    release_time = models.TimeField(default=time(hour=12))

    current_count = models.PositiveSmallIntegerField(default=0)
    total_count = models.PositiveSmallIntegerField(default=0)

    poster = models.ImageField(editable=True,
                               upload_to=poster_path,
                               storage=OverwriteStorage())

    media_type = models.ForeignKey(MediaType,
                                   help_text="Series' media type")

    media_type_options = JSONField(blank=True,
                                   help_text="A JSON object of options"
                                   " made available from the media type")

    NONE = 'N'
    WEEKLY = 'W'
    FORTNIGHTLY = 'F'
    MONTHLY = 'M'
    DISCRETE = 'D'
    RELEASE_SCHEDULE_CHOICES = (
        (NONE, _('None')),
        (WEEKLY, _('Weekly')),
        (FORTNIGHTLY, _('Fortnightly')),
        (MONTHLY, _('Monthly')),
        (DISCRETE, _('Discrete')),
    )
    release_schedule = models.CharField(max_length=1,
                                        default=WEEKLY,
                                        choices=RELEASE_SCHEDULE_CHOICES)
    release_schedule_options = JSONField(blank=True,
                                         help_text="A JSON object of needed"
                                         " info for each type of release schedule")

    def clean(self):
        if type(self.total_count) is not type(None):
            if self.current_count < 0:
                raise ValidationError('Currnet count cannot be below zero')
            if self.total_count < 0:
                raise ValidationError('Currnet count cannot be below zero')
            if self.current_count > self.total_count != 0:
                raise ValidationError('Current count cannot be bigger than total count, unless total count is zero')

        if type(self.end_date) is not type(None):
            if self.start_date > self.end_date:
                raise ValidationError('Start date cannot be greater than end date')

    def next_release(self):
        """
        Calculate the datetime of the next release of the series

        Returns:
            Return a DateTime object of the next next_release
            If the series is finished airing will return None
        """
        if self.start_date is None:
            return None

        if self.has_ended():
            return None

        if not self.has_started():
            return datetime.combine(self.start_date, self.release_time)

        # is airing

        release_date = self.start_date
        delta = None
        if self.release_schedule == Series.WEEKLY:
            delta = relativedelta(days=7)
        elif self.release_schedule == Series.FORTNIGHTLY:
            delta = relativedelta(days=14)
        elif self.release_schedule == Series.MONTHLY:
            delta = relativedelta(months=1)
        else:
            return None

        while datetime.combine(release_date, self.release_time) < datetime.now():
            release_date += delta

        release_datetime = datetime.combine(release_date, self.release_time)
        return release_datetime

    def has_started(self):
        """
        Boolean of if the series has started airing/publishing

        Note:
            uses release_time for time of day
        """
        return self.start_date is not None and  \
               timezone.now() >= timezone.make_aware(
                   datetime.combine(self.start_date, self.release_time))

    def has_ended(self):
        """
        Boolean of if the series has ended airing/publishing

        Note:
            uses release_time for time of day
        """
        if self.total_count != 0 and self.current_count >= self.total_count:
            return True

        if self.end_date is not None:
            return timezone.now() > timezone.make_aware(
                   datetime.combine(self.end_date, self.release_time))

        return False

    def is_airing(self):
        """
        Boolean of if the series is currently airing/publishing

        note:
            relies on has_started() and has_ended()
        """
        return self.has_started() and not self.has_ended()

    def __str__(self):
        return "{} ({})".format(self.title, self.provider.name)

    def bootstrap_label_class(self):
        """
        Generate HTML class for label for bootstrap 3
        """
        if self.is_airing():
            return 'label-success'
        if self.has_ended():
            return 'label-danger'
        if not self.has_started():
            return 'label-info'

    def label_text(self):
        """
        Generate HTML class for label for bootstrap 3
        """
        if self.is_airing():
            return _('Airing')
        if self.has_ended():
            return _('Finished')
        if not self.has_started():
            return _('Yet to air')

    def bootstrap_progressbar(self):
        """
        Generate HTML for a progress bar for bootstrap 3
        """
        text = ""
        sr = ""
        pb_class = "progress-bar-success"
        value = self.current_count
        max = self.total_count

        if self.total_count == 0:
            pb_class = "progress-bar-warning progress-bar-striped"
            value = self.current_count
            max = self.current_count
            prec = 100
        else:
            prec = round(value/max * 100)

        return """
        <div class="progress">
            <div class="progress-bar {pb_class}" role="progressbar" aria-valuenow="{value}" aria-valuemin="0" aria-valuemax="{max}" style="width: {prec}%">
                <span class="sr-only">{sr}</span>
                {text}
            </div>
        </div>
        """.format(pb_class=pb_class,
                   value=value,
                   max=max,
                   prec=prec,
                   sr=sr,
                   text=text)

    def release_schedule_options_json(self):
        """
        dumps release_schedule as json
        """
        return json.dumps(self.release_schedule_options)

    def media_type_options_json(self):
        """
        dumps media_type_options as json
        """
        return json.dumps(self.media_type_options)

    def info_url_domain(self):
        if type(self.info_url) is str:
            return re.sub('^.*://', '', self.info_url).split('/')[0]

series/models/media_types.py
import json

from django.db import models

from app.validators import json_schema_validator
from jsonfield import JSONField

_default='''{
    "properties":
    {
        "id": {
            "title": "ID",
            "type": "integer"
            }
    },
    "required": ["id"]
}'''

class MediaType(models.Model):
    """
    Over arching difference between series
    provides more options for different media types
    """
    name = models.CharField(max_length=80,
                            help_text="Name of the media type")
    available_options = JSONField(help_text="A JSON schema of options that"
                                  " the media type allows",
                                  validators=[json_schema_validator],
                                  default=_default)

    def __str__(self):
        return self.name

    def get_available_options(self):
        return json.dumps(self.available_options)

series/views.py
from datetime import datetime, timedelta
import json

from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from series.models import Series, MediaType
from series.forms import SeriesForm


def index(request):
    series = sorted(Series.objects.all(), key=lambda s: s.next_release() if type(s.next_release()) is datetime else datetime.max)

    if request.method == 'GET':
        filter = request.GET.get('filter')
        if filter:
            if filter == 'week':
                series = [s for s in series if type(s.next_release()) is datetime and \
                          s.next_release().date() <= (datetime.now().date() + timedelta(days=7))]

    if request.META.get('CONTENT_TYPE') == 'application/json':
        return render(request, 'series/index.json',
                      {'series': series},
                      content_type='application/json')
    else:
        return render(request, 'series/index.html',
                      {'series': series})


def view(request, series_id):
    series = get_object_or_404(Series, pk=series_id)
    return render(request, 'series/view.html',
                  {'series': series})


def new(request):
    form = SeriesForm()
    if request.method == 'POST':
        form = SeriesForm(request.POST, request.FILES)
        if form.is_valid():
            series = form.save(commit=False)
            if 'poster' in request.FILES:
                series.poster = request.FILES['poster']
            series.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 "<strong>Success</strong> Created {}"
                                 .format(series.title))
            return HttpResponseRedirect(reverse('series:view',
                                        args=[series.id]))

    return render(request, 'series/new.html',
                  {'form': form})


def edit(request, series_id):
    series = get_object_or_404(Series, pk=series_id)
    form = SeriesForm(instance=series)
    if request.method == 'POST':
        form = SeriesForm(request.POST, request.FILES, instance=series)
        if form.is_valid():
            if form.has_changed():
                form.save()
                messages.add_message(request,
                                     messages.SUCCESS,
                                     "<strong>Success</strong> Edited {}"
                                     .format(series.title))
            return HttpResponseRedirect(reverse('series:view',
                                                args=[series.id]))
    return render(request, 'series/edit.html',
                  {'series': series,
                   'form': form})


def delete(request, series_id):
    if request.method == 'POST':
        series = get_object_or_404(Series, pk=series_id)
        messages.add_message(request,
                             messages.INFO,
                             "{} has been deleted"
                             .format(series.title))
        series.delete()
        return HttpResponseRedirect(reverse('series:index'))
    else:
        return HttpResponseRedirect(reverse('series:view',
                                            args=(series_id)))


def media_type_index(request):
    if request.META.get('CONTENT_TYPE') == 'application/json':
        return render(request, 'series/media_index.json',
                      {'media_types': MediaType.objects.all()},
                      content_type='application/json')
    return render(request, 'series/media_index.html',
                  {'media_types': MediaType.objects.all()})


def media_type_view(request, media_type_id):
    media_type = get_object_or_404(MediaType, pk=media_type_id)
    if request.META.get('CONTENT_TYPE') == 'application/json':
        return render(request, 'series/media_view.json',
                      {'media_type': media_type},
                      content_type='application/json')
    return render(request, 'series/media_view.html',
                  {'media_type': media_type})

@csrf_exempt
def count(request, series_id):
    """
    Update a series current count if a valid change
    """
    series = get_object_or_404(Series, pk=series_id)
    if request.method == 'POST':
        try:
            try:
                print(request.body)
                body = json.loads(request.body.decode('utf-8'))
            except ValueError as e:
                return HttpResponse(json.dumps({'success': False, 'error': 'invalid json ' + str(e)}),
                                    content_type="application/json")
            if 'current_count' in body:
                current_count = int(body['current_count'])
                series.current_count = current_count
                series.clean()
                series.save()
                return HttpResponse(json.dumps({'success': True, 'current_count': series.current_count}),
                                    content_type="application/json")

            return HttpResponse(json.dumps({'success': False, 'error': 'no current_count'}),
                                content_type="application/json")
        except ValueError:
            return HttpResponse(json.dumps({'success': False, 'error': 'current count must be an int'}),
                                content_type="application/json")
        except Exception as e:
            return HttpResponse(json.dumps({'success': False, 'error': str(e)}), content_type="application/json")
    else:
        return HttpResponse(json.dumps({'current_count': series.current_count,
                                        'total_count': series.total_count}),
                            content_type="application/json")

series/templates/series/edit.html
{% extends 'series/index.html' %}
{% load bootstrap3 %}

{% block title %}
Series - Edit {{ series.title }}
{% endblock title %}

{% block extra_header %}
{{ form.media }}
{% endblock extra_header %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'series:index' %}">Series</a></li>
  <li><a href="{% url 'series:view' series.id %}">{{ series.title }}</a></li>
  <li class="active">Edit</li>
</ol>
{% endblock breadcrumb %}

{% block header %}
<h1>Edit {{ series.title }}</h1>
{% endblock header %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <form action="{% url 'series:edit' series.id %}" method="post" enctype="multipart/form-data" class="form well">
      {% csrf_token %}
      {% include 'series/form_series.html' with form=form %}

      <div class="row">
        <div class="col-md-12">
          <a href="{% url 'series:index' %}" class="btn btn-default">
            Back
          </a>
          <button type="submit" class="btn btn-primary pull-right">
            Sumbit
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

series/templates/series/form_series.html
{% load bootstrap3 %}
{% load staticfiles %}
{{ form.media }}

{% bootstrap_form_errors form %}
<div class="row">
  <div class="col-md-6">
    {% bootstrap_field form.title %}
  </div>
  <div class="col-md-6">
    {% bootstrap_field form.info_url %}
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    {% bootstrap_field form.provider %}
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    {% bootstrap_label form.poster.label %}
    {% bootstrap_field form.poster layout='inline' %}
  </div>
  <div class="col-md-6">
    {% bootstrap_label form.poster_url.label %}
    {% bootstrap_field form.poster_url layout='inline' %}
  </div>
  {{ form.poster.errors }}
</div>

<div class="row">
  <div class="col-sm-4">
    {% bootstrap_field  form.current_count %}
  </div>
  <div class="col-md-2"></div>
  <div class="col-sm-4">
    {% bootstrap_field  form.total_count %}
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    {% bootstrap_field  form.start_date %}
  </div>
  <div class="col-sm-6">
    {% bootstrap_field  form.end_date %}
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    {% bootstrap_field form.search_title %}
  </div>
  <div class="col-md-6">
    {% bootstrap_field form.save_path %}
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    {% bootstrap_field  form.release_schedule %}
    {{ form.release_schedule_options.errors }}
  </div>
  <div class="col-md-6">
    {% bootstrap_field  form.release_time %}
  </div>
</div>


<div class="row">
  <div id="release_schedule_options" class="col-md-6" >
    {% if series and not series.release_schedule_options == None %}
    {% for opt, val in series.release_schedule_options.items %}
      <input name="{{ opt }}" value="{{ val }}"></input>
    {% endfor %}
    {% else %}
    <p>Loading additional options</p>
    {% endif %}
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    {% bootstrap_field  form.media_type %}
    {{ form.media_type_options.errors }}
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <div id="media_type_options">
        {% if series and not series.media_type_options == None %}
        {% for opt, val in series.media_type_options.items %}
          <input name="{{ opt }}" value="{{ val }}"></input>
        {% endfor %}
        {% else %}
        <p>Loading additional options</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% bootstrap_field  form.media_type_options %}
{% bootstrap_field  form.release_schedule_options %}

<script type="text/javascript" src="{% static 'lib/json-form/deps/underscore.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/json-form/deps/opt/jsv.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/json-form/lib/jsonform.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/json-form/lib/jsonform-defaults.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/json-form/lib/jsonform-split.js' %}"></script>

<script type="text/javascript" src="{% static 'js/options.js' %}"></script>
<script type="text/javascript">
  $('#id_start_date').change(function() {
    // Need to use input#ID to get value because DateWidget generates a div with the same id
    $('#id_end_date').datetimepicker('setStartDate', $('input#id_start_date')[0].value);
  });
  $('#id_end_date').change(function(ev) {
    $('#id_start_date').datetimepicker('setEndDate', $('input#id_end_date')[0].value);
  });
  $('#id_start_date').ready(function() {
    $('#id_start_date').change();
  });
  $('#id_end_date').ready(function() {
    $('#id_end_date').change();
  });
</script>

<script type="text/javascript">
  change_trigger('#id_release_schedule', {{ form.generate_release_schedule_options|safe }}, '#release_schedule_options', '#id_release_schedule_options');
  change_trigger('#id_media_type', '{% url "series:media_index" %}', '#media_type_options', '#id_media_type_options');

    $('#id_media_type').ready(function() {
      $('#id_media_type').change();
    });
    $('#id_release_schedule').ready(function() {
      $('#id_release_schedule').change();
    });
</script>

series/templates/series/index.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
Series - Index
{% endblock title %}

{% block navbar_items %}
<li class="active"><a href="{% url 'series:index' %}">Series</a></li>
<li><a href="{% url 'provider:index' %}">Providers</a></li>
<li><a href="{% url 'fetcher:index' %}">Fetcher</a></li>
{% endblock navbar_items %}

{% block header %}
<h1>Series
  <div class="pull-right">
    <a href="{% url 'series:new' %}" class="btn btn-success">
      Create
    </a>
  </div>
</h1>
{% endblock header %}

{% block content %}
<ul class="series-list">
  {% for s in series %}
  <li>
    {% include "series/series_card.html" with series=s %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

series/templates/series/media_index.html
{% extends 'series/index.html' %}

{% block title %}
Series - Media Type - Index
{% endblock title %}

{% block header %}
<h1>Media Type</h1>
{% endblock header %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li ><a href="{% url 'series:index' %}">Series</a></li>
  <li class="active">Media Type</li>
</ol>
{% endblock breadcrumb %}

{% block content %}
{% if media_types|length == 0 %}
<h4>No Media Types available</h4>
<p>Please add some</p>
{% else %}
<ul>
  {% for media_type in media_types %}
  <li><a href="{% url 'series:media_view' media_type.id %}">{{ media_type }}</a></li>
  {% endfor %}
</ul>
{% endif %}
{% endblock content %}

series/templates/series/media_view.html
{% extends 'series/index.html' %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li ><a href="{% url 'series:index' %}">Series</a></li>
  <li ><a href="{% url 'series:media_index' %}">Media Type</a></li>
  <li class="active">{{ media_type.name }}</li>
</ol>
{% endblock breadcrumb %}

{% block header %}
<h1>
  {{ media_type.name }}
</h1>
{% endblock header %}

{% block content %}
<ul>
  <li>Available Options: <code>{{ media_type.get_available_options }}</code></a></li>
</ul>
{% endblock content %}

series/templates/series/new.html
{% extends 'series/index.html' %}
{% load bootstrap3 %}

{% block title %}
Series - New
{% endblock title %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'series:index' %}">Series</a></li>
  <li class="active">New</li>
</ol>
{% endblock breadcrumb %}

{% block header %}
<h1>Add Series</h1>
{% endblock header %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <form action="{% url 'series:new' %}" method="post" enctype="multipart/form-data" class="form well">
      {% csrf_token %}
      {% include 'series/form_series.html' with form=form %}

      <div class="row">
        <div class="col-md-12">
          <a href="{% url 'series:index' %}" class="btn btn-default">
            Back
          </a>
          <button type="submit" class="btn btn-primary pull-right">
            Sumbit
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

series/templates/series/series_card.html
<div class="panel panel-default">
  <a href="{% url 'series:view' series.id %}" >
    <div class="panel-body poster-area">
      {% if series.poster %}
      <img src="{{ series.poster.url }}" class="poster">
      {% endif %}
    </div>
  </a>
  <div class="panel-footer">
    <h4 class="truncate">
      <a title="{{ series.title }}" href="{% url 'series:view' series.id %}">
        {{ series.title }}
      </a>
      <br />
      <a title="{{ series.provider.name }}" href="{% url 'provider:view' series.provider.id %}">
        <small>
          {{ series.provider.name }}
        </small>
      </a>
    </h4>
    <p>
      <small>{% if series.next_release %}Next release: {{ series.next_release|date:"d-m" }}{% else %}&nbsp;{% endif %}</small>
      <span class="pull-right">
        {%if series.info_url %}
        <a href="{{ series.info_url }}"><span class="glyphicon glyphicon-info-sign"></span></a>
        {% endif %}
        <span class="label label-default"> {{ series.current_count }}/{%if series.total_count == 0 %}?{% else %}{{ series.total_count }}{% endif %}</span>
        <span class="label {{ series.bootstrap_label_class }}">{{ series.label_text }}</span>
      </span>
    </p>
    {{ series.bootstrap_progressbar|safe }}
  </div>
</div>

series/templates/series/view.html
{% extends 'series/index.html' %}
{% load staticfiles %}

{% block title %}
Series - {{ series.title }}
{% endblock title %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li ><a href="{% url 'series:index' %}">Series</a></li>
  <li class="active">{{ series.title }}</li>
</ol>
{% endblock breadcrumb %}

{% block header %}
<h1>
  {{ series.title }}
  <small>({{ series.provider.name }})</small>
</h1>
{% endblock header %}

{% block content %}
<div class="row">
    {% if series.poster %}
    <div class="col-md-4 col-md-fit">
        <img class="poster-full"  src="{{ series.poster.url }}">
    </div>
    {% endif %}
  <div class="col-md-3">
    <table>
      <tr>
        <td><strong>Provider</strong></td>
        <td><a href="{% url 'provider:view' series.provider.id %}">{{ series.provider.name }}</a></td>
      </tr>
      {% if series.info_url %}
      <tr>
        <td><strong>Information URL</strong></td>
        <td><a href="{{ series.info_url }}">{{ series.info_url_domain }}</a></td>
      </tr>
      {% endif %}
      {% if series.search_title %}
      <tr>
        <td><strong>Search Title</strong></td>
        <td>{{ series.search_title }}</td>
      </tr>
      {% endif %}
      {% if series.save_path %}
      <tr>
        <td><strong>Save Path</strong></td>
        <td>{{ series.save_path }}</td>
      </tr>
      {% endif %}
      <tr>
        <td><strong>Media Type</strong></td>
        <td>{{ series.media_type }}</td>
      </tr>
      <tr>
        <td><strong>Start Date</strong></td>
        <td>{{ series.start_date|date }}</td>
      </tr>
      <tr>
        <td><strong>End Date</strong></td>
        <td>{{ series.end_date|date }}</td>
      </tr>
      <tr>
        <td><strong>Release Time</strong></td>
        <td>{{ series.release_time|time }}</td>
      </tr>
      <tr>
        <td><strong>Is Airing</strong></td>
        <td>{{ series.is_airing }}</td>
      </tr>
      <tr>
        <td><strong>Has Started</strong></td>
        <td>{{ series.has_started }}</td>
      </tr>
      <tr>
        <td><strong>Has ended</strong></td>
        <td>{{ series.has_ended }}</td>
      </tr>
      <tr>
        <td><strong>Next Release</strong></td>
        <td>{{ series.next_release|date:"DATETIME_FORMAT" }}</td>
      </tr>
      <tr>
        <td><strong>Episode Count</strong></td>
        <td>
            <span><span id="series-current">{{ series.current_count }}</span>/{%if series.total_count == 0 %}?{% else %}{{ series.total_count }}{% endif %}</span>
            <button id="series-plus" class="btn btn-xs btn-default" type="button">+1</button>
        </td>
      </tr>
      <tr>
        <td><strong>Release Schedule</strong></td>
        <td>{{ series.release_schedule }}</td>
      </tr>
      <tr>
        <td><strong>Release Schedule Options</strong></td>
        <td><code>{{ series.release_schedule_options }}</code></td>
      </tr>
      <tr>
        <td><strong>Media Type Options</strong></td>
        <td><code>{{ series.media_type_options }}</code></td>
      </tr>
    </table>
    <div class="row" id="view-controls">
      <div class="col-lg-12">
        <a href="{% url 'series:index' %}" class="btn btn-default">
          Back
        </a>
        <a href="{% url 'series:edit' series.id %}" class="btn btn-warning">
          Edit
        </a>
        <button type="button" class="btn btn-danger btn-sm pull-right" data-toggle="modal" data-target="#modal-delete">
          Delete
        </button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Are you sure?</h3>
      </div>
      <div class="modal-body">
        <p>
          Are you sure you want to delete {{ series.title }}?
        </p>
      </div>
      <div class="modal-footer">
        <form action="{% url 'series:delete' series.id %}" method="post">
          {% csrf_token %}
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal" >Close</button>
          <button type="submit" class="btn btn-danger">
            Delete
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block extra_script %}
<script src="{% static 'series/js/view.js' %}"></script>
{% endblock extra_script%}